### ISSUE TITLE
Reduce build times by decoupling CI for each image and using cache

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/daaas-containers#22]
As most commits here will modify one image at a time, we can add  a `docker pull` to a `latest` tag of all images before building.  This will pull a latest version, which if unchanged will match the current and avoid having to rebuild.

Can also break each build into its own workflow yml, which allows for them to go in parallel.

If possible, moving this to an `acr build` would remove the need to transfer most data and speed builds up considerably for unchanged images.

**Comment by blairdrummond** [comment]
Think this is resolved for now by a parallel build. We could add more caching too, but think it's already pretty fast
